Repository italia-opensource/awesome-italia-opensource, pull requests merged in 2022-10, with the labels that each got.

#59 Update tiledesk.json
  data/tiledesk.json
Labels: feature: fix project

#58 fix: replace startups with innovative companies and fix broken link
  website/docusaurus.config.js
  website/src/pages/index.tsx
Labels: bug

#60 feat: add http-bee-request
  data/http-bee-request.json
Labels: feature: new project

#61 add nuvola project
  data/primait-nuvola.json
Labels: feature: new project
