Repository italia-opensource/awesome-italia-opensource, pull requests merged in 2022-09, with the labels that each got.

#1 Feat/clean website
  CONTRIBUTING.md
  cli.py
  data/bootstrap-italia.json
  website/blog/2019-05-28-first-blog-post.md
  website/blog/2019-05-29-long-blog-post.md
  website/blog/2021-08-01-mdx-blog-post.mdx
  website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  website/blog/2021-08-26-welcome/index.md
  website/blog/authors.yml
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/components/NewsletterForm/index.tsx
  website/src/components/NewsletterForm/styles.module.css
  website/src/css/custom.css
  website/src/pages/index.tsx
  website/static/img/.gitkeep
  website/static/img/docusaurus.png
  website/static/img/favicon.ico
  website/static/img/logo.svg
  website/static/img/undraw_docusaurus_mountain.svg
  website/static/img/undraw_docusaurus_react.svg
  website/static/img/undraw_docusaurus_tree.svg
Labels: feature

#2 feat: add pytorch deep learning
  CONTRIBUTING.md
  cli.py
  data/pytorch-deep-learning.json
Labels: feature

#3 feat: add projects
  CONTRIBUTING.md
  cli.py
  data/arduino.json
  data/io-app.json
  data/italiaremote.json
  data/pyxis.json
  data/redis.json
Labels: feature

#5 Create yamlinc.json
  data/yamlinc.json
Labels: feature: new project

#9 Hotfix/data files error
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  cli.py
  data/.gitkeep
  data/arduino.json
  data/bootstrap-italia.json
  data/io-app.json
  data/italiaremote.json
  data/kafka-connect-elasticsearch-source.json
  data/nuvolaris.json
  data/pytorch-deep-learning.json
  data/pyxis.json
  data/redis.json
Labels: bug

#7 Fix: typo on repository link
  .github/PULL_REQUEST.md
  CONTRIBUTING.md
  README.md
  cli.py
  website/docusaurus.config.js
Labels: bug

#8 feat: adding kamaji
  data/kamaji.json
Labels: feature: new project

#10 feat: adding capsule
  data/capsule.json
Labels: feature: new project

#11 feature: add schrodinger-hat project
  data/ImageGoNord.json
  data/daje.json
  data/snackjob.json
  data/youtube-to-anchorfm.json
Labels: feature: new project

#4 feat: add kannon
  data/kannon.json
Labels: feature: new project

#13 Feat/add project description
  CONTRIBUTING.md
  cli.py
  data/image-go-nord.json
  website/src/components/TableFeatures/index.tsx
Labels: feature

#14 add: fastify
  data/fastify.json
Labels: feature: new project

#16 Feat/add new sections website
  CONTRIBUTING.md
  cli.py
  website/src/components/TableFeatures/index.tsx
  website/src/css/custom.css
  website/src/pages/index.tsx
Labels: feature

#15 add: Icaro
  data/icaro.json
Labels: feature: new project

#17 Add Strawberry GraphQL
  data/strawberry-graphql.json
Labels: feature: new project

#18 fead: adding new projects
  data/autocannon.json
  data/make-promises-safe.json
  data/middy.json
Labels: feature: new project

#19 feat: adding new projects
  cli.py
  data/caronte.json
  data/ercole.json
  data/espanso.json
  data/hanami.json
  data/hitolab.json
  data/notable.json
  data/simple-ehm.json
Labels: feature: new project

#20 add: Kathará
  data/kathara.json
Labels: feature: new project

#22 Added Breathly
  data/breathly.json
Labels: feature: new project

#23 Added Remotebear
  data/remotebear.json
Labels: feature: new project

#21 Added Ordinary Puzzles
  data/ordinary-puzzles.json
Labels: feature: new project

#24 feat: adding style
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/test.yml
  CONTRIBUTING.md
  cli.py
Labels: feature

#25 Added project Pet Therapy
  data/pet-therapy.json
Labels: feature: new project

#26 add comuni istat api project
  data/comuni-istat-api.json
Labels: feature: new project

#30 feat: add OpenGeoData project
  data/open-geo-data.json
Labels: feature: new project

#33 Add dgc.json
  data/dgc.json
Labels: feature: new project

#35 add kube-green
  data/kube-green.json
Labels: feature: new project

#34 Micro lc
  data/micro-lc.json
Labels: feature: new project

#37 feat: add new section to readme
  cli.py
  data/nuvolaris.json
  data/yamlinc.json
Labels: feature: request

#38 Add 2ami
  data/2ami.json
Labels: feature: new project

#42 Create tiledesk.json
  data/tiledesk.json
Labels: feature: new project

#43 feat: add gushio.json
  data/gushio.json
Labels: feature: new project

#44 feat: add leapp.json
  data/leapp.json
Labels: feature: new project

#45 Comuni istat api
  data/comuni-istat-api.json
Labels: feature: fix project

#46 feat(fix): copy
  CONTRIBUTING.md
  website/src/pages/index.tsx
Labels: feature: request

#47 Add cachegrand.json
  data/cachegrand.json
Labels: feature: new project

#48 feat: integrate awesome startups
  .github/ISSUE_TEMPLATE/QUESTION.yml
  CONTRIBUTING.md
  website/docusaurus.config.js
  website/src/pages/index.tsx
Labels: feature: request

#49 feat: add kong
  data/kong.json
Labels: feature: new project

#50 feat: add python faker
  data/faker.json
Labels: feature: new project

#52 Adding new Italian projects
  data/arduino-desk-weatherstation.json
  data/covid19-Monitoring.json
Labels: feature: new project

#54 feat: add copyleft licenses
  CONTRIBUTING.md
  cli.py
Labels: feature: request

#55 Create mobilizon-reshare.json
  data/mobilizon-reshare.json
Labels: feature: new project

#56 update icaro info
  data/icaro.json
Labels: feature: fix project

#57 feat: add spooq
  data/spooq.json
Labels: feature: new project
