Repository italia-opensource/awesome-italia-opensource, pull requests merged in 2023-02, with the labels that each got.

#69 hotifx: release workflow
  .github/workflows/release.yml
Labels: bug

#66 feat: add orchy
  awesome/opensource/data/orchy-mfe.json
Labels: feature: new project

#71 docs: fixed typo
  README.md
Labels: refactoring

#68 Add Argon
  awesome/opensource/data/argon.json
Labels: feature: new project

#72 docs: fixed typos in contributing
  CONTRIBUTING.md
Labels: refactoring

#73 Added company Opencity Labs and SaaS Product Opencity Italia
  awesome/companies/data/opencity-labs.json
  awesome/opensource/data/opencity-italia.json
Labels: feature: new project

#76 Create advigator.json
  awesome/companies/data/advigator.json
Labels: feature: new project
